services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  db:
    image: 'ttonylee/techecho_postgres_image'
    container_name: postgres_container_with_data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

